default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5433
  username: aitah_player
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aitah_player
  password: password


test:
  <<: *default
  database: aitah_player
  password: password

#production:
#  <<: *default
#  database: aitah_player_production
#  username: aitah_player
#  password: <%#= ENV["RAILS_TEST_JSBUNDLING_DATABASE_PASSWORD"] %>
